spring.data.mongodb.uri=mongodb://localhost:27017/onboarding
app.frontend.url=http://localhost:5173

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=tonemail@gmail.com
spring.mail.password=motdepasse_app
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true